services:
  - type: web
    name: forher
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NOTIFICATION_EMAIL
        value: gangamvarun5@gmail.com
