services:
  - type: web
    name: forher
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false